### ISSUE TITLE
stale-while-revalidate

### ISSUE THREAD

**Issue by rogueturnip** [gmpassos/mercury_client#2]
Does the in memory cache work like a stale-while-revalidate cache?  RFC 5861 https://tools.ietf.org/html/rfc5861

I just am curious if I can use the cached data to show the UI and it will update once the new data comes in.

**Comment by gmpassos** [comment]
Good idea. I'm implementing something similar, where it notifies if you can use a temporary version of what is cached.

**Comment by gmpassos** [comment]
I have released `mercury_client` `v.2.1.0`, with stale response notification:
https://pub.dev/packages/mercury_client
