### ISSUE TITLE
Optimistic UI

### ISSUE THREAD

**Issue by rogueturnip** [gmpassos/mercury_client#3]
The library is really getting great!  I was wondering if it supports optimistic UI for Post and Put requests?  An example of a React Native library I've used is:
https://swr.vercel.app/docs/mutation

You can specify the successful response while the api updates and returns the results.  Also with the ability to say if you just want to use the specified data or actually revalidate it.

**Comment by gmpassos** [comment]
I will take a look.

See the stale request support:
https://github.com/gmpassos/mercury_client#httpcache-usage

Send some feedback of the feature.

**Comment by rogueturnip** [comment]
Thanks!  You bet!  This is the first API library I've found that has good momentum to really give REST the same abilities of some of the more advanced graphql libraries.

**Comment by gmpassos** [comment]
If you can create more examples and improve the README will be good for new users. If you need any help just ask.

**Comment by gmpassos** [comment]
See:
https://pub.dev/packages/async_field

and
https://pub.dev/packages/async_extension
